"""ICS-214 / 209 / 204 form generators (tw-vem9, tw-5hq).

MVP scope (tw-vem9): ICS-214 Activity Log only, markdown output.

The data comes from the existing audit_event table. Op-period filtering
is by query-string start_iso / end_iso since tw-eebq (first-class
op-period concept) is post-MVP per ADR 0014.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlmodel import Session, select

from target_workspace.api.dependencies import db_session, require_token_scope
from target_workspace.db.tables import (
    AuditEventTable,
    BoardTable,
    ColumnTable,
    TargetTable,
    UserTable,
)

router = APIRouter(prefix="/v1/boards", tags=["forms"])


def _render_ics214_markdown(
    *,
    board_name: str,
    incident_name: str,
    prepared_by: str,
    period_start: str | None,
    period_end: str | None,
    rows: list[dict[str, Any]],
) -> str:
    lines: list[str] = []
    lines.append("# ICS-214 — Activity Log")
    lines.append("")
    lines.append(f"**Incident:** {incident_name}")
    lines.append(f"**Board:** {board_name}")
    lines.append(f"**Prepared by:** {prepared_by}")
    if period_start or period_end:
        lines.append(
            f"**Operational period:** {period_start or 'open'} → {period_end or 'open'}",
        )
    lines.append("")
    lines.append("| Time (UTC) | Actor | Event | Details |")
    lines.append("|---|---|---|---|")
    for row in rows:
        details = []
        if row.get("from_column_id"):
            details.append(f"from={row['from_column_id']}")
        if row.get("to_column_id"):
            details.append(f"to={row['to_column_id']}")
        if row.get("justification"):
            details.append(f"reason={row['justification']}")
        meta = row.get("metadata") or {}
        for k, v in meta.items():
            details.append(f"{k}={v}")
        lines.append(
            "| {time} | {actor} | {event} | {details} |".format(
                time=row.get("occurred_at", ""),
                actor=row.get("actor_id") or "-",
                event=row.get("event_type", ""),
                details=", ".join(str(d) for d in details) or "-",
            ),
        )
    lines.append("")
    lines.append("---")
    lines.append("Generated by Target Workspace ICS-214 export (tw-vem9).")
    return "\n".join(lines)


@router.get("/{board_id}/forms/ics-214")
def get_ics214(
    board_id: UUID,
    start_iso: str | None = Query(default=None, alias="start_iso"),
    end_iso: str | None = Query(default=None, alias="end_iso"),
    session: Session = Depends(db_session),
    user: UserTable = Depends(require_token_scope("forms:read")),
) -> Response:
    """Return the ICS-214 Activity Log for a board as markdown.

    Query parameters:
      start_iso, end_iso — optional ISO-8601 timestamps to bound the
        op-period window. When omitted, returns all events for the board.

    Per tw-vem9 (ADR 0014 hybrid): markdown only at MVP; PDF deferred.
    """
    board = session.get(BoardTable, board_id)
    if board is None or board.workspace_id != user.workspace_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="board not found")

    stmt = select(AuditEventTable).where(AuditEventTable.workspace_id == user.workspace_id)
    if start_iso:
        try:
            start_dt = datetime.fromisoformat(start_iso.replace("Z", "+00:00"))
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"invalid start_iso: {exc}",
            ) from exc
        stmt = stmt.where(AuditEventTable.occurred_at >= start_dt.replace(tzinfo=None))
    if end_iso:
        try:
            end_dt = datetime.fromisoformat(end_iso.replace("Z", "+00:00"))
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"invalid end_iso: {exc}",
            ) from exc
        stmt = stmt.where(AuditEventTable.occurred_at <= end_dt.replace(tzinfo=None))
    stmt = stmt.order_by(AuditEventTable.occurred_at.asc())  # type: ignore[attr-defined]
    rows = session.exec(stmt).all()

    payload_rows = [
        {
            "occurred_at": r.occurred_at.isoformat() if r.occurred_at else "",
            "actor_id": str(r.actor_id) if r.actor_id else None,
            "event_type": r.event_type,
            "from_column_id": str(r.from_column_id) if r.from_column_id else None,
            "to_column_id": str(r.to_column_id) if r.to_column_id else None,
            "justification": r.justification,
            "metadata": dict(r.metadata_json or {}),
        }
        for r in rows
    ]
    body = _render_ics214_markdown(
        board_name=board.name,
        incident_name=board.name,
        prepared_by=user.display_name,
        period_start=start_iso,
        period_end=end_iso,
        rows=payload_rows,
    )
    return Response(
        content=body,
        media_type="text/markdown; charset=utf-8",
    )


# ──────────────────────────────────────────────────────────────────────────
# ICS-209 — Incident Status Summary (tw-5hq)
# ──────────────────────────────────────────────────────────────────────────


def _render_ics209_markdown(
    *,
    board_name: str,
    prepared_by: str,
    column_counts: list[tuple[str, int]],
    recent_audit_count: int,
    period_label: str | None,
) -> str:
    lines: list[str] = []
    lines.append("# ICS-209 — Incident Status Summary")
    lines.append("")
    lines.append(f"**Incident:** {board_name}")
    lines.append(f"**Prepared by:** {prepared_by}")
    if period_label:
        lines.append(f"**Operational period:** {period_label}")
    lines.append("")
    lines.append("## Current resource counts (by column)")
    lines.append("")
    lines.append("| Column | Count |")
    lines.append("|---|---|")
    total = 0
    for name, n in column_counts:
        lines.append(f"| {name} | {n} |")
        total += n
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")
    lines.append("## Activity volume")
    lines.append("")
    lines.append(f"- Audit events in window: {recent_audit_count}")
    lines.append("")
    lines.append("---")
    lines.append("Generated by Target Workspace ICS-209 export (tw-5hq).")
    return "\n".join(lines)


@router.get("/{board_id}/forms/ics-209")
def get_ics209(
    board_id: UUID,
    start_iso: str | None = Query(default=None),
    end_iso: str | None = Query(default=None),
    session: Session = Depends(db_session),
    user: UserTable = Depends(require_token_scope("forms:read")),
) -> Response:
    """ICS-209 Incident Status Summary as markdown. Per tw-5hq.

    Counts targets by column (current snapshot) + audit volume in the
    optional date window. ICS-204 (assignment list) requires resource
    entities (tw-auf + tw-qkp) and is a follow-up.
    """
    board = session.get(BoardTable, board_id)
    if board is None or board.workspace_id != user.workspace_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="board not found")

    columns = session.exec(
        select(ColumnTable).where(ColumnTable.board_id == board_id).order_by(ColumnTable.order),  # type: ignore[arg-type]
    ).all()
    counts: list[tuple[str, int]] = []
    for c in columns:
        n = len(
            session.exec(
                select(TargetTable).where(TargetTable.column_id == c.id),
            ).all(),
        )
        counts.append((c.name, n))

    audit_stmt = select(AuditEventTable).where(
        AuditEventTable.workspace_id == user.workspace_id,
    )
    period_label = None
    if start_iso:
        try:
            sdt = datetime.fromisoformat(start_iso.replace("Z", "+00:00"))
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"invalid start_iso: {exc}",
            ) from exc
        audit_stmt = audit_stmt.where(
            AuditEventTable.occurred_at >= sdt.replace(tzinfo=None),
        )
        period_label = f"{start_iso} → {end_iso or 'open'}"
    if end_iso:
        try:
            edt = datetime.fromisoformat(end_iso.replace("Z", "+00:00"))
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"invalid end_iso: {exc}",
            ) from exc
        audit_stmt = audit_stmt.where(
            AuditEventTable.occurred_at <= edt.replace(tzinfo=None),
        )

    recent_audit_count = len(session.exec(audit_stmt).all())

    body = _render_ics209_markdown(
        board_name=board.name,
        prepared_by=user.display_name,
        column_counts=counts,
        recent_audit_count=recent_audit_count,
        period_label=period_label,
    )
    return Response(content=body, media_type="text/markdown; charset=utf-8")
