"""baseline schema

Revision ID: d1a95d61de4d
Revises:
Create Date: 2026-05-17 14:32:56.847374
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "d1a95d61de4d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "board",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transitions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_board_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "promotion_policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min_confidence", sa.Float(), nullable=True),
        sa.Column("required_stages", sa.JSON(), nullable=True),
        sa.Column("approval_roles", sa.JSON(), nullable=True),
        sa.Column("auto_publish_column_id", sa.Uuid(), nullable=True),
        sa.Column("on_low_confidence_route_to_column_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("promotion_policy", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_promotion_policy_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "publisher_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plugin_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("adapter_config", sa.JSON(), nullable=True),
        sa.Column("column_filter_ids", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publisher_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publisher_config_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "source_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plugin_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("adapter_config", sa.JSON(), nullable=True),
        sa.Column("normalization_map", sa.JSON(), nullable=True),
        sa.Column("promotion_policy_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_config_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "column",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("wip_limit", sa.Integer(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["board.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_column_board_id"), ["board_id"], unique=False)

    op.create_table(
        "target",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column("column_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("hae", sa.Float(), nullable=True),
        sa.Column("ce", sa.Float(), nullable=True),
        sa.Column("le", sa.Float(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("stale", sa.DateTime(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("geometry_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ellipse", sa.JSON(), nullable=True),
        sa.Column("polygon_vertices", sa.JSON(), nullable=True),
        sa.Column("geometry_quality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["board.id"],
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_target_board_id"), ["board_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_target_column_id"), ["column_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_target_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("from_column_id", sa.Uuid(), nullable=True),
        sa.Column("to_column_id", sa.Uuid(), nullable=True),
        sa.Column("justification", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_event_target_id"), ["target_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "track_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("hae", sa.Float(), nullable=True),
        sa.Column("ce", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("classification", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("track_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_observation_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_track_observation_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_track_observation_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_observation_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_track_observation_target_id"))
        batch_op.drop_index(batch_op.f("ix_track_observation_observed_at"))

    op.drop_table("track_observation")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_event_actor_id"))

    op.drop_table("audit_event")
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_target_column_id"))
        batch_op.drop_index(batch_op.f("ix_target_board_id"))

    op.drop_table("target")
    with op.batch_alter_table("column", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_column_board_id"))

    op.drop_table("column")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("source_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_config_workspace_id"))

    op.drop_table("source_config")
    with op.batch_alter_table("publisher_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publisher_config_workspace_id"))

    op.drop_table("publisher_config")
    with op.batch_alter_table("promotion_policy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotion_policy_workspace_id"))

    op.drop_table("promotion_policy")
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_workspace_id"))

    op.drop_table("board")
    op.drop_table("workspace")
    # ### end Alembic commands ###
