"""add user.enabled + user.deleted_at

Revision ID: e68a488a8214
Revises: f272605d88b4
Create Date: 2026-05-18 00:04:56.753375
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  — registers SQLModel column types for autogen
from alembic import op

revision: str = "e68a488a8214"
down_revision: str | Sequence[str] | None = "f272605d88b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # enabled MUST have a server_default so existing rows backfill to
    # True on the NOT NULL ALTER. Without it the migration fails on any
    # populated user table.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            ),
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("enabled")

    # ### end Alembic commands ###
