"""add target.position for within-column ordering

Revision ID: f272605d88b4
Revises: d1a95d61de4d
Create Date: 2026-05-17 16:41:19.537714
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  — registers SQLModel column types for autogen
from alembic import op

revision: str = "f272605d88b4"
down_revision: str | Sequence[str] | None = "d1a95d61de4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add the column with a server_default so existing rows backfill to
    # 0.0 in place. Without it the NOT NULL ALTER would fail on any
    # populated DB.
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "position",
                sa.Float(),
                nullable=False,
                server_default="0.0",
            )
        )
        batch_op.create_index(batch_op.f("ix_target_position"), ["position"], unique=False)

    # Seed each column's targets with distinct positions so the first
    # drag-reorder has stable midpoints to compute against. Use
    # created_at as the natural baseline order.
    op.execute(
        """
        UPDATE target
        SET position = (
            SELECT COUNT(*)
            FROM target AS t2
            WHERE t2.column_id = target.column_id
              AND t2.created_at <= target.created_at
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_position"))
        batch_op.drop_column("position")

    # ### end Alembic commands ###
